apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
  subscriptions: |
    - recipients:
      - slack:test-channel
      triggers:
      - on-sync-succeeded
      - on-sync-failed
      - on-sync-status-unknown
      - on-health-degraded
  triggers.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - slack
      when: app_status.operation.phase in ['Succeeded'] and app_status.operation.sync.kind in ['sync']
  triggers.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - slack
      when: app_status.operation.phase in ['Failed', 'Error'] and app_status.operation.sync.kind in ['sync']
  triggers.on-health-degraded: |
    - description: Application has degraded
      send:
      - slack
      when: app_status.health.status == 'Degraded'
