apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-root
  namespace: argocd
  labels:
    environment: stage
spec:
  project: default
  source:
    repoURL: https://github.com/rattandevesh/gitops.git
    targetRevision: HEAD
    path: apps/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
