apiVersion: v1
kind: Secret
metadata:
  name: prod-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: prod.cluster.example.internal
  server: https://api.prod.cluster.example.internal
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "prod.cluster.example.internal"
      },
      "tlsClientConfig": {
        "insecure": false
      }
    }
