apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - platform-application.yaml
  - ui-application.yaml
  - catalog-application.yaml
  - cart-application.yaml
  - orders-application.yaml
  - checkout-application.yaml
  - monitoring-application.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/source/helm/valueFiles/0
        value: values-dev.yaml
    target:
      kind: Application
